micronaut:
  application:
    name: minder-api

jackson:
  serialization:
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false

jpa:
  default:
    entity-scan:
      packages: 'co.newlabs.minder'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2